version: '3.4'

services:
  gathermesuggestionms:
    image: gathermesuggestionms
    build:
      context: .
      dockerfile: gatherme-suggestion-ms/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
